name: SwiftLint

on: [push, pull_request]

jobs:
  build:
    runs-on: macOS-latest
    timeout-minutes: 10
    
    strategy:
      fail-fast: true
    steps:
    
    - uses: actions/checkout@v3

    # Set up Node.js version 16
    - uses: actions/setup-node@v3
      with:
        node-version: '16'

    # Install SwiftLint
    - name: Install SwiftLint
      run: brew install swiftlint

    # Run SwiftLint
    - name: Run SwiftLint
      run: swiftlint

